# Generated by Django 5.2.15 on 2026-06-04 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, default='')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('has_hepatitis', models.BooleanField(default=False)),
                ('has_hiv', models.BooleanField(default=False)),
                ('has_heart_disease', models.BooleanField(default=False)),
                ('recent_surgery', models.BooleanField(default=False)),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('medical_notes', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
