# Generated by Django 5.2.15 on 2026-06-07 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodunit',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='expiry_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('issued', 'Issued'), ('expired', 'Expired')], db_index=True, default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
